[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = [
    "-Clink-arg=-Wl,-undefined,dynamic_lookup",
    "-L/opt/homebrew/Cellar/libsixel/1.10.3_1/lib/",
]
